pipeline_name: "test-batch-pipeline"

output_dir: "./examples/test_batch/output"

stages:
  - name: "loader"
    stage_type: "ImageLoader"
    config:
      resize: [640, 480]

  - name: "filter"
    stage_type: "SimpleFilter"
    config:
      kernel_size: 5

connections:
  - source: "loader"
    target: "filter"
    output_key: "image"
    input_key: "image"

batch_config:
  input_dir: "./examples/test_batch/input"
  output_dir: "./examples/test_batch/output"
  file_patterns:
    - "*.jpg"
    - "*.jpeg"
    - "*.png"
  recursive: true
  continue_on_error: true
  report_output: "batch_report.html"
