# Point cloud batch processing configuration
pipeline_name: "pointcloud-batch-pipeline"
output_dir: "./output"

stages:
  - name: loader
    stage_type: PointCloudLoader
    config:
      downsample_voxel_size: 0.05
      remove_outliers: true
      outlier_neighbors: 20
      outlier_std_ratio: 2.0

  - name: validator
    stage_type: PointCloudValidationStage
    config:
      rules:
        min_points: 10
        max_points: 10000000
        check_nan: true
        check_inf: true
        fail_fast: false
      raise_on_invalid: false

  - name: thumbnail
    stage_type: PointCloudThumbnailStage
    config:
      viewpoints: ["diagonal"]
      width: 400
      height: 300
      point_size: 2.0
      background_color: [1.0, 1.0, 1.0]

connections:
  - source: loader
    target: validator
    output_key: points
    input_key: points

  - source: loader
    target: thumbnail
    output_key: points
    input_key: points

batch_config:
  input_dir: "./tests/fixtures/sample_pointclouds"
  output_dir: "./examples/test_pointcloud_batch/output"
  file_patterns:
    - "*.pcd"
    - "*.ply"
  recursive: false
  continue_on_error: true
  report_output: "pointcloud_report.html"
  output_mode: "sample"
  save_outputs:
    enabled: true
    stages: ["all"]
    max_samples: 100
    format: "ply"
